name: Staging Deployment CI/CD

on:
  push:
    branches: [main]
  workflow_dispatch:
    logLevel:
    description: 'Log level'
    required: false
    default: 'warning'
    type: choice
    options:
      - info
      - warning
      - debug
jobs:
  build_push_deploy:
    env:
      DOCKER_REPO: 'vinhluong0147'
      DOCKER_IMAGE: 'nestjs-project'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./deployment/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}/${{ env.DOCKER_IMAGE }}:staging-latest
            ${{ env.DOCKER_REPO }}/${{ env.DOCKER_IMAGE }}:staging-0.1.${{github.run_number}}
